/*
Meridian Time Group - 2026 H1 actuals incremental load
Appends six new months (January through June 2026) of transactional
actuals to an existing SQL Server instance built from the original
meridian schema, the same schema the T-SQL migration step is described as
building on the Data Foundation page.

This is an incremental append, not a rebuild. It does not touch any
2023-2025 rows in fact_boutique_sales or fact_sell_in, and it is written
to be safe to run more than once: each insert is guarded by a check for
rows that already exist in the target date range, so re-running this
script after a successful load is a no-op rather than a duplicate load.

Source data: the CSV files in the sqlserver_load_2026_h1 folder next to
this script, generated by generate_2026_h1_actuals.py from the same
meridian.db this SQL Server instance was originally migrated from.

Run order: dim_date, then fact_fx_rate, then the two sales facts, since
the facts join against both dimensions.
*/

SET NOCOUNT ON;

-- 1. dim_date: 181 new rows, 2026-01-01 through 2026-06-30
IF NOT EXISTS (SELECT 1 FROM dim_date WHERE date_id = 20260101)
BEGIN
    CREATE TABLE #stg_dim_date (
        date_id INT, full_date DATE, [day] INT, day_name NVARCHAR(20),
        week INT, [month] INT, month_name NVARCHAR(20), quarter INT,
        [year] INT, fiscal_year INT, fiscal_quarter INT, is_weekend BIT
    );

    BULK INSERT #stg_dim_date
    FROM 'sqlserver_load_2026_h1\dim_date_2026_h1.csv'
    WITH (FORMAT = 'CSV', FIRSTROW = 2, CODEPAGE = '65001');

    INSERT INTO dim_date (date_id, full_date, [day], day_name, week, [month],
        month_name, quarter, [year], fiscal_year, fiscal_quarter, is_weekend)
    SELECT date_id, full_date, [day], day_name, week, [month], month_name,
        quarter, [year], fiscal_year, fiscal_quarter, is_weekend
    FROM #stg_dim_date;

    DROP TABLE #stg_dim_date;
    PRINT 'dim_date: 2026 H1 rows loaded.';
END
ELSE
    PRINT 'dim_date: 2026 H1 rows already present, skipped.';
GO

-- 2. fact_fx_rate: 1,810 new rows (10 currencies x 181 days)
IF NOT EXISTS (SELECT 1 FROM fact_fx_rate WHERE date_id = 20260101)
BEGIN
    CREATE TABLE #stg_fx (
        date_id INT, currency_code NVARCHAR(3), rate_to_chf DECIMAL(18,6)
    );

    BULK INSERT #stg_fx
    FROM 'sqlserver_load_2026_h1\fact_fx_rate_2026_h1.csv'
    WITH (FORMAT = 'CSV', FIRSTROW = 2, CODEPAGE = '65001');

    INSERT INTO fact_fx_rate (date_id, currency_code, rate_to_chf)
    SELECT date_id, currency_code, rate_to_chf FROM #stg_fx;

    DROP TABLE #stg_fx;
    PRINT 'fact_fx_rate: 2026 H1 rows loaded.';
END
ELSE
    PRINT 'fact_fx_rate: 2026 H1 rows already present, skipped.';
GO

-- 3. fact_boutique_sales: 4,983 new rows, appended, 2023-2025 untouched
IF NOT EXISTS (SELECT 1 FROM fact_boutique_sales WHERE date_id = 20260101)
BEGIN
    CREATE TABLE #stg_boutique (
        date_id INT, store_id INT, sku_id NVARCHAR(10), units INT,
        gross_revenue_lc DECIMAL(18,2), discount_lc DECIMAL(18,2),
        net_revenue_lc DECIMAL(18,2), actual_unit_cost_chf DECIMAL(18,2),
        currency_code NVARCHAR(3), net_revenue_chf DECIMAL(18,2)
    );

    BULK INSERT #stg_boutique
    FROM 'sqlserver_load_2026_h1\fact_boutique_sales_2026_h1.csv'
    WITH (FORMAT = 'CSV', FIRSTROW = 2, CODEPAGE = '65001');

    INSERT INTO fact_boutique_sales (date_id, store_id, sku_id, units,
        gross_revenue_lc, discount_lc, net_revenue_lc, actual_unit_cost_chf,
        currency_code, net_revenue_chf)
    SELECT date_id, store_id, sku_id, units, gross_revenue_lc, discount_lc,
        net_revenue_lc, actual_unit_cost_chf, currency_code, net_revenue_chf
    FROM #stg_boutique;

    DROP TABLE #stg_boutique;
    PRINT 'fact_boutique_sales: 2026 H1 rows loaded.';
END
ELSE
    PRINT 'fact_boutique_sales: 2026 H1 rows already present, skipped.';
GO

-- 4. fact_sell_in: 11,206 new rows, appended, 2023-2025 untouched
IF NOT EXISTS (SELECT 1 FROM fact_sell_in WHERE date_id = 20260101)
BEGIN
    CREATE TABLE #stg_sell_in (
        date_id INT, customer_id INT, sku_id NVARCHAR(10), units INT,
        gross_revenue_lc DECIMAL(18,2), discount_lc DECIMAL(18,2),
        net_revenue_lc DECIMAL(18,2), actual_unit_cost_chf DECIMAL(18,2),
        currency_code NVARCHAR(3), net_revenue_chf DECIMAL(18,2)
    );

    BULK INSERT #stg_sell_in
    FROM 'sqlserver_load_2026_h1\fact_sell_in_2026_h1.csv'
    WITH (FORMAT = 'CSV', FIRSTROW = 2, CODEPAGE = '65001');

    INSERT INTO fact_sell_in (date_id, customer_id, sku_id, units,
        gross_revenue_lc, discount_lc, net_revenue_lc, actual_unit_cost_chf,
        currency_code, net_revenue_chf)
    SELECT date_id, customer_id, sku_id, units, gross_revenue_lc, discount_lc,
        net_revenue_lc, actual_unit_cost_chf, currency_code, net_revenue_chf
    FROM #stg_sell_in;

    DROP TABLE #stg_sell_in;
    PRINT 'fact_sell_in: 2026 H1 rows loaded.';
END
ELSE
    PRINT 'fact_sell_in: 2026 H1 rows already present, skipped.';
GO

-- 5. Verification: row counts and referential integrity for the new range
SELECT 'dim_date' AS table_name, COUNT(*) AS row_count FROM dim_date WHERE date_id BETWEEN 20260101 AND 20260630
UNION ALL
SELECT 'fact_fx_rate', COUNT(*) FROM fact_fx_rate WHERE date_id BETWEEN 20260101 AND 20260630
UNION ALL
SELECT 'fact_boutique_sales', COUNT(*) FROM fact_boutique_sales WHERE date_id BETWEEN 20260101 AND 20260630
UNION ALL
SELECT 'fact_sell_in', COUNT(*) FROM fact_sell_in WHERE date_id BETWEEN 20260101 AND 20260630;

SELECT COUNT(*) AS orphaned_boutique_rows
FROM fact_boutique_sales b
WHERE b.date_id BETWEEN 20260101 AND 20260630
  AND NOT EXISTS (SELECT 1 FROM dim_store s WHERE s.store_id = b.store_id)
   OR NOT EXISTS (SELECT 1 FROM dim_line l WHERE l.sku_id = b.sku_id);

SELECT COUNT(*) AS orphaned_sell_in_rows
FROM fact_sell_in f
WHERE f.date_id BETWEEN 20260101 AND 20260630
  AND NOT EXISTS (SELECT 1 FROM dim_wholesale_customer c WHERE c.customer_id = f.customer_id)
   OR NOT EXISTS (SELECT 1 FROM dim_line l WHERE l.sku_id = f.sku_id);
GO
